steps:
- name: 'gcr.io/project-mlops/docker'
  args: ['build', '-t', 'gcr.io/sunlit-apricot-411406/trainer', '.']
- name: 'gcr.io/project-mlops/docker'
  args: ['push', 'gcr.io/sunlit-apricot-411406/trainer']