steps:
- name: 'bash'
  script: 'ls -la'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'gs://mlops_project_data_bucket', './data']
- name: 'bash'
  script: 'mkdir models'
- name: 'bash'
  script: 'mv /data/models ./models'
- name: 'bash'
  script: 'ls -la'
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', '-r', 'gs://mlops_project_data_bucket/models', 'models/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sunlit-apricot-411406/trainer', '-f', 'dockerfiles/train_model.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sunlit-apricot-411406/trainer']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sunlit-apricot-411406/predict', '-f', 'dockerfiles/predict_model.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sunlit-apricot-411406/predict']
