workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-8
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/astute-anagram-410709/trainer-fake-news
        env:
            - name: "WANDB_API_KEY"
              value: "<Your WANDB API Key>"