name: "Code styling"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Check code style
      run: |
        ruff check
    - name: Format code style
      run: |
        ruff format
